### ISSUE TITLE
Fc3000 

### ISSUE THREAD

**Issue by aksenav2** [steward-fu/website#2]
Sorry for bothering, I haven't been able to solve the problem when compiling uboot for more than two weeks. Please tell me what the problem may be.
![IMG_20240123_142650](https://github.com/steward-fu/website/assets/110097689/0792dd03-030b-4f95-8a97-465609a902fd)

**Comment by aksenav2** [comment]
Previously, there was also a YYALOC error, but after downgrading the GCC-9, the error disappeared. 
![IMG_20240124_143832_196](https://github.com/steward-fu/website/assets/110097689/0ac0c0c0-5c12-411b-aeda-50c4e4a47a3f)

**Comment by aksenav2** [comment]
Bootloader, kernel I downloaded from your FC3000 archive. Toolchain was also downloaded from your github, when the link was still active.

**Comment by aksenav2** [comment]
Today I installed Debian 9 on the virtual machine - the kernel and boot were compiled without a single error. But when I installed the Debian 13 the same mistakes were made.

As far as I understand, some packages are missing, or does not work with new packages. Can you tell me what packages are needed for the work?

**Comment by steward-fu** [comment]
This issue is related to dtc (device tree compiler). May I know what kind of OS you are using ?

**Comment by aksenav2** [comment]
> This issue is related to dtc (device tree compiler). May I know what kind of OS you are using ?

I've already found a solution to this problem and have successfully compiled the kernel and bootloader. 
But now I'm having a problem with initializing the display. 
The console turns on correctly, but if you turn it off and on again, it turns on, after the first logo, with a white display, but the system is working correctly, you can start the game and you will hear a sound. But in order for the console to turn on correctly, you need to turn it off and wait for 5 minutes. 
And so it goes every time.

**Comment by steward-fu** [comment]
I think it may be related to the initial code of LCD. You can try to add sleep in each initial command.

**Comment by aksenav2** [comment]
> I think it may be related to the initial code of LCD. You can try to add sleep in each initial command.

I have a tft display, you can write an example of how to do it and in which code file. I'm just not very good at programming.

**Comment by aksenav2** [comment]
Also, in order for my console to start correctly, when compiling kernel, I need to enter the fc3000_ips1 parameters. And when I compile boot, I can ips1 or tft2 аnd there is no difference, and either way starts correctly. 
Although I dismantled the console and I have a display t2815-m110-24.
And my boot logo has a GRB color parameter, and the kernel is RGB

**Comment by steward-fu** [comment]
Could you please post the github link for your kernel and boot code ?

**Comment by aksenav2** [comment]
> Could you please post the github link for your kernel and boot code ?

I downloaded from your archive, this is your code. 

https://github.com/steward-fu/archives/releases/download/fc3000/bootloader-f1c100s_fc3000_uboot-2018.01.zip

https://github.com/steward-fu/archives/releases/download/fc3000/kernel-f1c100s_fc3000_linux-4.14.0.zip

**Comment by steward-fu** [comment]
In drivers/video/fbdev/sunivfb.c file, you can try to add mdelay() after command:
**lcdc_wr_cmd(swapRB(0xe7));
mdelay(1);**

**Comment by aksenav2** [comment]
No, it didn't help. 
![IMG_20240220_085551](https://github.com/steward-fu/website/assets/110097689/5e3e54a7-aa62-424c-8b81-a16e0b6fc491)

**Comment by aksenav2** [comment]
In this firmware, there is no such problem, but in it the start and select buttons work as a turbo (cycle press without stopping if pressed and held) 
https://github.com/steward-fu/archives/releases/download/fc3000/old_tft_od_no_roms.7z

**Comment by steward-fu** [comment]
I meant you should add sleep for each command to see whether this issue is fixed. All of LCD commands are found by reverse engineering method, therefore, it is hard to fix this issue unless reverse engineering again.

**Comment by aksenav2** [comment]
If you meant to do this after each line, it didn't help either. 
![IMG_20240227_092325](https://github.com/steward-fu/website/assets/110097689/c642ccfd-3763-49c6-861a-538e0f9ec80a)

**Comment by aksenav2** [comment]
On the old firmware, after the kernel logo, the display is completely turned off and initialized again. And on the new one, after the kernel logo, the display immediately tries to launch the console menu, and just at this moment the console does not have time to initialize the display.  Is it possible to add some kind of reset command?

**Comment by aksenav2** [comment]
Also, I noticed that the source code uses a display T2812_M106_24C
But I have a display in my console T2812_M110_24C. Maybe that's also the point? 
![Screenshot_2024-02-27-10-50-44-888_com miui gallery](https://github.com/steward-fu/website/assets/110097689/822b75e0-70b8-4887-8c40-9b8867ce1744)
![IMG_20240227_105059](https://github.com/steward-fu/website/assets/110097689/0003465a-7b41-4d2b-aea9-14eb25c9ebee)

**Comment by aksenav2** [comment]
Anyway, there's something messed up in the source code. Since in order for me to compile, for the display to work, I need to enter the command ./tools/make_suniv.sh. sh fc3000_ips1
And if I type ./tools/make_suniv.sh. sh fc3000_tft2 - then there is no image on the console at all and the display is not initialized.

**Comment by aksenav2** [comment]
![Uploading Screenshot_2024-02-27-14-18-51-856_com.miui.gallery.png…]()

**Comment by aksenav2** [comment]
![Screenshot_2024-02-27-14-18-51-856_com miui gallery](https://github.com/steward-fu/website/assets/110097689/fecb0d93-05d5-4292-9901-b25cd68a2336)

**Comment by aksenav2** [comment]
Thank you for telling me where to look for a solution to the problem. I also compared the display initialization parameters in the boot and kernel source code and found that delay was omitted to the kernel, while in the sours code boot this line was present. And gradually, making various changes, I achieved the optimal result and now, initialization of the display works in 99 percent of the inclusion. 
![IMG_20240227_160425](https://github.com/steward-fu/website/assets/110097689/075407bb-a8ce-48b7-9730-365cb008811e)

**Comment by steward-fu** [comment]
Congratulations and thanks for your sharing !

**Comment by aksenav2** [comment]
I also have an xyc q8 console. Actually, I packed my firmware. But recently I wanted to flash from your archive, but it is not working, some incomprehensible hybrid (fc3000 and xyc) Please check and fix it if possible. 

https://github.com/steward-fu/archives/releases/download/q8/q8_od_jutleys_no_roms.img.7z

**Comment by steward-fu** [comment]
These devices have been throw into trash can already. So, they will not get any update or fix.
