### ISSUE TITLE
how to use the rel_sorr_20231116.zip？

### ISSUE THREAD

**Issue by Windstarry** [steward-fu/website#4]
I found the rel_sorr_20231116.zip file at https://github.com/steward-fu/website/releases/tag/trimui-smart, how do I use this package in TrimUI，I noticed on the postmaster that sorr has not been adapted for trimUI yet, how can I play sorr on trimUI?Thanks~

**Comment by steward-fu** [comment]
Extract to 'Apps' folder and then you can see the SORR icon.
